/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tech: [
    {
      type: 'autogenerated',
      dirName: 'Tech',
    }
  ],
  music: [
    'Music/musicIntro',
    {
      'Jazz': ['Music/jazz/jazzPlaylist'],
    }
  ],
  others: [
    {
      type: 'autogenerated',
      dirName: 'Others',
    }
  ]
};

export default sidebars;
